
# Path to your data file (can be .parquet or .csv)
filepath: ""

target_column: "" # Replace with your actual target column name
columns_to_drop: ""                 # List columns you want to drop, or leave empty
  - ""
  - ""
  - ""
train_size: 0.8                   # Fraction of data for training
test_size: 0.2                    # Fraction of data for testing
random_state: 42                  # Random seed for reproducibility
is_classification: false          # Set to true if this is a classification problem
